adminop/urls.py
from adminop.views import OperatorDetailsView, OperatorView
from userapp.views import OrderDetailsView, OrderView
from django.urls import path

app_name = "operator"


urlpatterns = [
    path('', OperatorView.as_view(),
         name="reservations"),
    path('reservation//<int:pk>', OperatorDetailsView.as_view(),
         name="reservation-detail"),
]

fyfproject/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LoginView, LogoutView
from landing.views import SignUpView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("landing.urls", namespace="landing")),
    path('courses/', include("courses.urls", namespace="courses")),
    path('user/', include("userapp.urls", namespace="userapp")),
    path('operator/', include("adminop.urls", namespace="operator")),
    path('packages/', include("package_registration.urls", namespace="packages")),
    path('account/signup/', SignUpView.as_view(), name="signup"),
    path('accounts/', include('allauth.urls')),

]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

userapp/urls.py
from userapp.views import OrderDetailsView, OrderView
from django.urls import path

app_name = "userapp"


urlpatterns = [
    path('orders/', OrderView.as_view(),
         name="orders"),
    path('orders/<int:pk>', OrderDetailsView.as_view(),
         name="order-detail"),
]

userapp/models.py
from django.db import models

# Create your models here.

userapp/views.py
from datetime import date
from typing import Generic
from django.shortcuts import render
from django.views import generic
from package_registration.models import Package, Reservation, ReservationDives, ReservationEquipments, ReservationHotel
from datetime import datetime
from django.contrib.auth.mixins import LoginRequiredMixin

# Create your views here.


class OrderView(LoginRequiredMixin, generic.TemplateView):
    template_name = "userapp/order_history.html"

    def get_context_data(self, **kwargs):
        context = super(OrderView, self).get_context_data(**kwargs)

        reservation = Reservation.objects.filter(
            user=self.request.user).order_by("-pk")

        context.update({
            "reservations": reservation,
            "today": date.today()
        })
        return context


class OrderDetailsView(LoginRequiredMixin, generic.TemplateView):
    template_name = "userapp/order_details.html"

    def get_context_data(self, **kwargs):
        context = super(OrderDetailsView, self).get_context_data(**kwargs)
        total_price_dives = 0
        total_price_equipment = 0
        total_price_hotel = 0
        total_price = 0
        pk = self.kwargs["pk"]
        context = super(OrderDetailsView, self).get_context_data(**kwargs)
        dives = ReservationDives.objects.filter(reservation=pk)
        equipments = ReservationEquipments.objects.filter(reservation=pk)
        hotel = ReservationHotel.objects.get(reservation=pk)
        reservation = Reservation.objects.get(pk=pk)
        package = Package.objects.get(name=reservation.package)

        package_price = package.price

        for dive in dives:
            total_price_dives += dive.price

        for eq in equipments:
            total_price_equipment += eq.price

        total_price_hotel = hotel.price_hotel+hotel.price_room

        total_price = total_price_dives+total_price_equipment + \
            total_price_hotel+package_price

        context.update({
            "dives": dives,
            "equipments": equipments,
            "hotel": hotel,
            "reservation": reservation,
            "package_price": package_price,
            "price_hotel": total_price_hotel,
            "price_equipment": total_price_equipment,
            "price_dives": total_price_dives,
            "total_price": total_price

        })

        return context

userapp/templates/userapp/order_details.html
{% extends 'base.html' %}

{% load static %}
{% block title %}
<title>Trip details</title>
{% endblock title%}
{% block links %}

<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}" />
<link rel="stylesheet" href="{% static 'css/fonts.css' %}" />
<link rel="stylesheet" href="{% static 'css/style.css' %}" />
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css"
    integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous" />

<style>
    .ie-panel {
        display: none;
        background: #212121;
        padding: 10px 0;
        box-shadow: 3px 3px 5px 0 rgba(0, 0, 0, 0.3);
        clear: both;
        text-align: center;
        position: relative;
        z-index: 1;
    }

    html.ie-10 .ie-panel,
    html.lt-ie-10 .ie-panel {
        display: block;
    }
</style>

{% endblock links %}


{% block content %}
<!-- Breadcrumbs -->
<div class="card-body py-4">
    <div class="text-center">
        <span class="h3 d-block font-weight-bold">Reservations {{reservation.pk}} </span><span><a
                href="{% url 'userapp:orders' %}">Go back to your reservations</a></span>
    </div> <!-- Why choose us-->


    <section class="section section-sm section-first bg-default text-md-left">
        <div class="container">
            <div class="row row-50 justify-content-center align-items-xl-center">

                <div class="col-md-15 col-lg-12 col-xl-11">
                    <hr class="h3">
                    <div class="text-center">

                        <p class="lead text-danger ">Package base Price :
                            {{package_price}} $</p>
                        <p class="lead text-danger ">Total Dive Price : {{price_dives}} $
                        </p>
                        <p class="lead text-danger ">Total Equipment Price :
                            {{price_equipment}} $</p>
                        <p class="lead text-danger ">Hotel Price : {{price_hotel}} $</p>
                        <p class="lead text-danger font-weight-bold">Total Price : {{total_price}} $</p>
                    </div>
                    <hr class="h3">
                    <div class="text-center">
                        <span class="h4 d-block mt-5 mb-3 text-primary">Hotel</span>

                    </div>
                    <table class="table mb-4">

                        <thead class="thead-dark">
                            <tr>

                                <th scope="col">Hotel</th>
                                <th scope="col">Hotel name</th>
                                <th scope="col">Hotel website</th>
                                <th scope="col">Room</th>
                                <th class="text-right" scope="col">Price</th>


                            </tr>
                        </thead>

                        <tbody>

                            <tr>
                                <td> {{hotel.hotel}}</td>
                                <td> {{hotel.hotel_name}}</td>
                                <td> {{hotel.hotel_website}}</td>
                                <td> {{hotel.room}}</td>
                                <td class="text-right">{{price_hotel}} $</td>

                            </tr>


                        </tbody>
                    </table>
                    <div class="text-center">

                        <span class="h4 d-block mt-5 mb-3 text-primary">Dives</span>
                    </div>
                    <table class="table mb-4 ">
                        <thead class="thead-dark">
                            <tr>

                                <th scope="col">Dive Type</th>
                                <th class="text-right" scope="col">Price</th>

                            </tr>
                        </thead>

                        <tbody>
                            {% for dive in dives %}
                            <tr>
                                <td class="text-left"> {{dive.dives_name}}</td>
                                <td class="text-right"> {{dive.price}} $</td>

                            </tr>
                            {% endfor %}


                        </tbody>
                    </table>
                    <div class="text-center">
                        <span class="h4 d-block mt-5 mb-3 text-primary">Equipments</span>

                    </div>
                    <table class="table mb-4">

                        <thead class="thead-dark">
                            <tr>

                                <th scope="col">Equipment</th>
                                <th class="text-right" scope="col">Price</th>

                            </tr>
                        </thead>

                        <tbody>
                            {% for equipment in equipments %}
                            <tr>
                                <td class="text-left"> {{equipment.equipment_name}}</td>
                                <td class="text-right"> {{equipment.price}} $</td>

                            </tr>
                            {% endfor %}



                        </tbody>
                    </table>


                </div>
            </div>
        </div>
    </section>





    <footer class="section footer-corporate context-dark">
        <div class="footer-corporate-inset">
            <div class="container">
                <div class="row row-40 justify-content-lg-between">
                    <div class="col-sm-6 col-md-12 col-lg-3 col-xl-4">
                        <div class="oh-desktop">
                            <div class="wow slideInRight" data-wow-delay="0s">

                                <ul class="footer-contacts d-inline-block d-sm-block">
                                    <li>
                                        <h6 class="text-spacing-100 text-uppercase">Contact us</h6>
                                    </li>
                                    <li>
                                        <div class="unit">
                                            <div class="unit-left"><span class="icon fa fa-phone"></span></div>
                                            <div class="unit-body"><a class="link-phone" href="tel:#">+961
                                                    1-480-087</a>
                                            </div>
                                        </div>

                                    </li>
                                    <li>
                                        <div class="unit">
                                            <div class="unit-left"><span class="icon fa fa-envelope"></span>
                                            </div>
                                            <div class="unit-body"><a class="link-aemail"
                                                    href="mailto:#">info@aquaventurescubaacademy-lb.com</a>
                                            </div>
                                        </div>
                                    </li>

                                    <li>
                                        <div class="unit">
                                            <div class="unit-left"><span class="icon fa fa-location-arrow"></span></div>
                                            <div class="unit-body"><a class="link-location"
                                                    href="coming_soon.html">Bacha
                                                    Gardens 1st Floor,
                                                    NAUI office, Hazmieh, Lebanon</a></div>
                                        </div>
                                    </li>
                                    <li>
                                        <div class="unit">
                                            <div class="rd-navbar-brand">
                                                <!--Brand-->
                                            </div>
                                        </div>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-6 col-md-12 col-lg-3 col-xl-4">
                        <div class="oh-desktop">
                            <div class="wow slideInRight" data-wow-delay="0s">


                            </div>
                        </div>
                    </div>
                    <div class="col-sm-6 col-md-5 col-lg-3 col-xl-4">
                        <div class="oh-desktop">
                            <div class="wow slideInDown" data-wow-delay="0s">
                                <form>
                                    <h6 class="text-spacing-100 text-uppercase">Write us a feedback</h6>
                                    <!-- Post Minimal 2-->
                                    <article class="post post-minimal-2">
                                        <div class="form-group">
                                            <label for="exampleFormControlInput1">Email address</label>
                                            <input type="email" class="form-control" id="exampleFormControlInput1"
                                                placeholder="name@example.com">
                                        </div>
                                    </article>
                                    <!-- Post Minimal 2-->
                                    <article class="post post-minimal-2">
                                        <div class="form-group">
                                            <label for="exampleFormControlTextarea1">Message</label>
                                            <textarea class="form-control" id="exampleFormControlTextarea1"></textarea>
                                            <div class="group-md group-middle justify-content-sm-start"><button
                                                    class="button button-lg button-primary button-ujarak"
                                                    href="coming_soon.html" type="submit">Submit</button></div>

                                        </div>
                                    </article>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="footer-corporate-bottom-panel">
            <div class="container">
                <div class="row justfy-content-xl-space-berween row-10 align-items-md-center2">
                    <div class="col-sm-6 col-md-4 text-sm-right text-md-center">
                        <div>
                            <ul class="list-inline list-inline-sm footer-social-list-2">
                                <li><a class="icon fa fa-facebook" href="#"></a></li>
                                <li><a class="icon fa fa-twitter" href="#"></a></li>
                                <li><a class="icon fa fa-google-plus" href="#"></a></li>
                                <li><a class="icon fa fa-instagram"
                                        href="https://www.instagram.com/findyourfinsinlebanon/"></a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-sm-6 col-md-4 order-sm-first">
                        <!-- Rights-->
                        <p class="rights"><span>&copy;&nbsp;</span><span
                                class="copyright-year"></span><span>&nbsp;</span><span>Find
                                Your Fins</span>. All Rights Reserved. Design by Patrick Saade</p>
                    </div>
                    <div class="col-sm-6 col-md-4 text-md-right">
                        <p class="rights"><a href="#">Privacy Policy</a></p>

                    </div>
                </div>
            </div>
        </div>
    </footer>
</div>
<!-- Global Mailform Output-->
<div class="snackbars" id="form-output-global"></div>
{% endblock content %}
{% block script %}
<script src="{% static 'js/core.min.js' %}"></script>
<script src="{% static 'js/script.js' %}"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js"
    integrity="sha384-SR1sx49pcuLnqZUnnPwx6FCym0wLsk5JZuNx2bPPENzswTNFaQU1RDvt3wT4gWFG" crossorigin="anonymous">
</script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.min.js"
    integrity="sha384-j0CNLUeiqtyaRmlzUHCPZ+Gy5fQu0dQ6eZ/xAww941Ai1SxSY+0EQqNXNE6DZiVc" crossorigin="anonymous">
</script>

{% endblock script %}

userapp/templates/userapp/order_history.html
{% extends 'base.html' %}

{% load static %}
{% block title %}
<title>Trips</title>
{% endblock title%}
{% block links %}

<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}" />
<link rel="stylesheet" href="{% static 'css/fonts.css' %}" />
<link rel="stylesheet" href="{% static 'css/style.css' %}" />
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css"
    integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous" />

<style>
    .ie-panel {
        display: none;
        background: #212121;
        padding: 10px 0;
        box-shadow: 3px 3px 5px 0 rgba(0, 0, 0, 0.3);
        clear: both;
        text-align: center;
        position: relative;
        z-index: 1;
    }

    html.ie-10 .ie-panel,
    html.lt-ie-10 .ie-panel {
        display: block;
    }
</style>

{% endblock links %}



{% block content %}
<!-- Breadcrumbs -->
<div class="card-body py-4">
    <div class="text-center">
        <span class="h3 d-block font-weight-bold">Your Reservations</span>
        <span class="h5 text-danger">We will send you an email once the hotel is confirmed</span>
    </div>
    <!-- Why choose us-->
    <section class="section section-sm section-first bg-default text-md-left">
        <div class="container">
            <div class="row row-50 justify-content-center align-items-xl-center">

                <div class="col-md-15 col-lg-12 col-xl-11">
                    {% for res in reservations  %}
                    {% if res.arrival_date > today  %}
                    <table class="table mb-5">
                        <thead class="thead-light">
                            <tr>
                                <th scope="col">ID</th>
                                <th scope="col">Email</th>
                                <th scope="col">Price($)</th>
                                <th scope="col">Packages</th>
                                <th scope="col">Date and time</th>
                                <th scope="col">Status</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <th scope="row"><a href="{% url 'userapp:order-detail' res.pk %}">{{res.pk}}</a></th>
                                <td>{{res.user}}</td>
                                <td>{{res.total_price}}</td>
                                <td>{{res.package}}</td>
                                <td>{{res.arrival_date}} {{res.arrival_time}}</td>
                                <td class="text-success">Incoming trip</td>
                            </tr>
                        </tbody>
                    </table>
                    {% else %}



                    <table class="table mb-5">
                        <thead class="thead-light">
                            <tr>
                                <th scope="col">ID</th>
                                <th scope="col">Email</th>
                                <th scope="col">Price($)</th>
                                <th scope="col">Packages</th>
                                <th scope="col">Date and time</th>
                                <th scope="col">Status</th>


                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <th scope="row"><a href="{% url 'userapp:order-detail' res.pk %}">{{res.pk}}</a></th>
                                <td>{{res.user}}</td>
                                <td>{{res.total_price}}</td>
                                <td>{{res.package}}</td>
                                <td>{{res.arrival_date}} {{res.arrival_time}}</td>
                                <td class="text-danger">Previous trip</td>
                            </tr>
                        </tbody>
                    </table>





                    {% endif %}
                    {% endfor %}

                </div>
            </div>
        </div>
    </section>





    <footer class="section footer-corporate context-dark">
        <div class="footer-corporate-inset">
            <div class="container">
                <div class="row row-40 justify-content-lg-between">
                    <div class="col-sm-6 col-md-12 col-lg-3 col-xl-4">
                        <div class="oh-desktop">
                            <div class="wow slideInRight" data-wow-delay="0s">

                                <ul class="footer-contacts d-inline-block d-sm-block">
                                    <li>
                                        <h6 class="text-spacing-100 text-uppercase">Contact us</h6>
                                    </li>
                                    <li>
                                        <div class="unit">
                                            <div class="unit-left"><span class="icon fa fa-phone"></span></div>
                                            <div class="unit-body"><a class="link-phone" href="tel:#">+961 1-480-087</a>
                                            </div>
                                        </div>

                                    </li>
                                    <li>
                                        <div class="unit">
                                            <div class="unit-left"><span class="icon fa fa-envelope"></span></div>
                                            <div class="unit-body"><a class="link-aemail"
                                                    href="mailto:#">info@aquaventurescubaacademy-lb.com</a></div>
                                        </div>
                                    </li>

                                    <li>
                                        <div class="unit">
                                            <div class="unit-left"><span class="icon fa fa-location-arrow"></span></div>
                                            <div class="unit-body"><a class="link-location"
                                                    href="coming_soon.html">Bacha
                                                    Gardens 1st Floor,
                                                    NAUI office, Hazmieh, Lebanon</a></div>
                                        </div>
                                    </li>
                                    <li>
                                        <div class="unit">
                                            <div class="rd-navbar-brand">
                                                <!--Brand-->
                                            </div>
                                        </div>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-6 col-md-12 col-lg-3 col-xl-4">
                        <div class="oh-desktop">
                            <div class="wow slideInRight" data-wow-delay="0s">


                            </div>
                        </div>
                    </div>
                    <div class="col-sm-6 col-md-5 col-lg-3 col-xl-4">
                        <div class="oh-desktop">
                            <div class="wow slideInDown" data-wow-delay="0s">
                                <form>
                                    <h6 class="text-spacing-100 text-uppercase">Write us a feedback</h6>
                                    <!-- Post Minimal 2-->
                                    <article class="post post-minimal-2">
                                        <div class="form-group">
                                            <label for="exampleFormControlInput1">Email address</label>
                                            <input type="email" class="form-control" id="exampleFormControlInput1"
                                                placeholder="name@example.com">
                                        </div>
                                    </article>
                                    <!-- Post Minimal 2-->
                                    <article class="post post-minimal-2">
                                        <div class="form-group">
                                            <label for="exampleFormControlTextarea1">Message</label>
                                            <textarea class="form-control" id="exampleFormControlTextarea1"></textarea>
                                            <div class="group-md group-middle justify-content-sm-start"><button
                                                    class="button button-lg button-primary button-ujarak"
                                                    href="coming_soon.html" type="submit">Submit</button></div>

                                        </div>
                                    </article>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="footer-corporate-bottom-panel">
            <div class="container">
                <div class="row justfy-content-xl-space-berween row-10 align-items-md-center2">
                    <div class="col-sm-6 col-md-4 text-sm-right text-md-center">
                        <div>
                            <ul class="list-inline list-inline-sm footer-social-list-2">
                                <li><a class="icon fa fa-facebook" href="#"></a></li>
                                <li><a class="icon fa fa-twitter" href="#"></a></li>
                                <li><a class="icon fa fa-google-plus" href="#"></a></li>
                                <li><a class="icon fa fa-instagram"
                                        href="https://www.instagram.com/findyourfinsinlebanon/"></a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-sm-6 col-md-4 order-sm-first">
                        <!-- Rights-->
                        <p class="rights"><span>&copy;&nbsp;</span><span
                                class="copyright-year"></span><span>&nbsp;</span><span>Find
                                Your Fins</span>. All Rights Reserved. Design by Patrick Saade</p>
                    </div>
                    <div class="col-sm-6 col-md-4 text-md-right">
                        <p class="rights"><a href="#">Privacy Policy</a></p>

                    </div>
                </div>
            </div>
        </div>
    </footer>
</div>
<!-- Global Mailform Output-->
<div class="snackbars" id="form-output-global"></div>
{% endblock content %}
{% block script %}
<script src="{% static 'js/core.min.js' %}"></script>
<script src="{% static 'js/script.js' %}"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js"
    integrity="sha384-SR1sx49pcuLnqZUnnPwx6FCym0wLsk5JZuNx2bPPENzswTNFaQU1RDvt3wT4gWFG" crossorigin="anonymous">
</script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.min.js"
    integrity="sha384-j0CNLUeiqtyaRmlzUHCPZ+Gy5fQu0dQ6eZ/xAww941Ai1SxSY+0EQqNXNE6DZiVc" crossorigin="anonymous">
</script>

{% endblock script %}