adminop/urls.py
from adminop.views import OperatorDetailsView, OperatorView
from userapp.views import OrderDetailsView, OrderView
from django.urls import path

app_name = "operator"


urlpatterns = [
    path('', OperatorView.as_view(),
         name="reservations"),
    path('reservation//<int:pk>', OperatorDetailsView.as_view(),
         name="reservation-detail"),
]

fyfproject/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LoginView, LogoutView
from landing.views import SignUpView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("landing.urls", namespace="landing")),
    path('courses/', include("courses.urls", namespace="courses")),
    path('user/', include("userapp.urls", namespace="userapp")),
    path('operator/', include("adminop.urls", namespace="operator")),
    path('packages/', include("package_registration.urls", namespace="packages")),
    path('account/signup/', SignUpView.as_view(), name="signup"),
    path('accounts/', include('allauth.urls')),

]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

package_registration/urls.py
from package_registration.views import BookRegistration, PaymentView, SummaryView
from django.urls import path

app_name = "packages"


urlpatterns = [
    path('registration/<int:pk>', BookRegistration,
         name="package-registration"),
    path('summary/<int:pk>', SummaryView.as_view(),
         name="registration-summary"),
    path('payment/<int:pk>', PaymentView.as_view(),
         name="registration-payment")




]

package_registration/models.py
from django.db import models
from landing.models import User

# Create your models here.

DIVING_TYPES = [
    ("Entry-Level", "Entry-Level"),
    ("Specialty", "Specialty"),
    ("Leadership", "Leadership"),
    ("Technical Diver", "Technical Diver"),
    ("Continuing Education", "Continuing Education"),
    ("First Aid", "First Aid"),
    ("Support Course", "Support Course"),
    ("Instructor Specialty", "Instructor Specialty"),
    ("Recognition", "Recognition"),
    ("Supervised Diver", "Supervised Diver"),
    ("Public Safety Diving", "Public Safety Diving"),
    ("Freediving", "Freediving"),


]


EQUIPMENT = [
    ("Full equipment", "Full equipment"),
    ("Normal", "Normal"),
    ("No equipment", "No equipment")
]


class Package(models.Model):
    name = models.CharField(max_length=120)
    price = models.DecimalField("Price in $",
                                max_digits=6, decimal_places=2, null=True, blank=True)

    def __str__(self) -> str:
        return self.name


class Accomodation(models.Model):
    name = models.CharField(max_length=120)
    price = models.DecimalField("Price in $",
                                max_digits=6, decimal_places=2, null=True, blank=True)

    def __str__(self) -> str:
        return self.name


class Equipement(models.Model):
    name = models.CharField(max_length=120)
    price = models.DecimalField(
        "Price in $", max_digits=6, decimal_places=2, null=True, blank=True)
    type = models.CharField(max_length=120, null=True,
                            blank=True, choices=EQUIPMENT)

    def __str__(self) -> str:
        return self.name


class DiveType(models.Model):
    name = models.CharField(max_length=120)
    price = models.DecimalField("Price in $",
                                max_digits=6, decimal_places=2, null=True, blank=True)
    level = models.CharField(max_length=120, null=True,
                             blank=True, choices=DIVING_TYPES)

    def __str__(self) -> str:
        return self.name


class Room(models.Model):
    name = models.CharField(max_length=120)
    price = models.DecimalField("Price in $",
                                max_digits=6, decimal_places=2, null=True, blank=True)

    def __str__(self) -> str:
        return self.name


class Reservation(models.Model):
    user = models.ForeignKey(
        User, blank=True, null=True, on_delete=models.CASCADE)
    total_price = models.DecimalField("Total price in $",
                                      max_digits=6, decimal_places=2, null=True, blank=True)
    date_reservation = models.DateTimeField(auto_now_add=True, editable=True)
    package = models.ForeignKey(
        Package, blank=True, null=True, on_delete=models.CASCADE)
    arrival_date = models.DateField(null=True, blank=True, editable=True)

    arrival_time = models.TimeField(blank=True, null=True)

    status = models.CharField(max_length=120, null=True, blank=True)

    def __str__(self) -> str:
        return str(self.pk)


class ReservationDives(models.Model):
    dives_name = models.ForeignKey(
        DiveType, blank=True, null=True, on_delete=models.CASCADE)
    reservation = models.ForeignKey(
        Reservation, null=True, blank=True, on_delete=models.CASCADE)
    price = models.DecimalField("Price in $",
                                max_digits=6, decimal_places=2, null=True, blank=True)

    def __str__(self) -> str:
        return self.dives_name.name


class ReservationEquipments(models.Model):
    equipment_name = models.ForeignKey(
        Equipement, blank=True, null=True, on_delete=models.CASCADE)
    reservation = models.ForeignKey(
        Reservation, null=True, blank=True, on_delete=models.CASCADE)
    price = models.DecimalField("Price in $",
                                max_digits=6, decimal_places=2, null=True, blank=True)


class ReservationHotel(models.Model):
    hotel = models.ForeignKey(
        Accomodation, blank=True, null=True, on_delete=models.CASCADE)
    room = models.ForeignKey(
        Room, blank=True, null=True, on_delete=models.CASCADE)
    price_hotel = models.DecimalField("Price in $",
                                      max_digits=6, decimal_places=2, null=True, blank=True)
    price_room = models.DecimalField("Price in $",
                                     max_digits=6, decimal_places=2, null=True, blank=True)
    hotel_name = models.CharField(max_length=120, blank=True, null=True)
    hotel_website = models.URLField(max_length=200, blank=True, null=True)
    reservation = models.ForeignKey(
        Reservation, null=True, blank=True, on_delete=models.CASCADE)

package_registration/forms.py
from django import forms


class dummy(forms.Form):
    dummy = None

package_registration/views.py
from package_registration.forms import dummy
from django.http.request import HttpRequest
from django.http.response import HttpResponse
from package_registration.models import Accomodation, DiveType, Equipement, Package, Reservation, ReservationDives, ReservationEquipments, ReservationHotel, Room
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views import generic
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.mail import EmailMultiAlternatives
from django.template.loader import get_template
from django.template import Context
from django.conf import settings


# Create your views here. package_registration/package_registration.html"


def BookRegistration(request, pk):

    accomodations = Accomodation.objects.all().order_by("name")
    rooms = Room.objects.all()

    entry_level = DiveType.objects.filter(level="Entry-Level")
    specialty_level = DiveType.objects.filter(level="Specialty")
    leadership_level = DiveType.objects.filter(level="Leadership")
    technical_level = DiveType.objects.filter(level="Technical Diver")
    freediving_level = DiveType.objects.filter(level="Freediving")
    aid_level = DiveType.objects.filter(level="First Aid")
    education_level = DiveType.objects.filter(level="Continuing Education")
    instructor_level = DiveType.objects.filter(level="Instructor Specialty")
    support_level = DiveType.objects.filter(level="Support Course")
    recognition_level = DiveType.objects.filter(level="Recognition")
    supervised_level = DiveType.objects.filter(level="Supervised Diver")
    public_level = DiveType.objects.filter(level="Public Safety Diving")

    equipements = Equipement.objects.all()
    personals = equipements.filter(type="Full equipment")
    essentials = equipements.filter(type="Normal")
    no_equipment = equipements.get(type="No equipment")

    context = {
        "accomodations": accomodations,
        "rooms": rooms,


        "divers_level": entry_level,
        "specialty_levels": specialty_level,
        "leadership_levels": leadership_level,
        "technical_levels": technical_level,
        "leadership_levels": leadership_level,
        "freediving_levels": freediving_level,
        "aid_levels": aid_level,
        "education_levels": education_level,
        "instructor_levels": instructor_level,
        "support_levels": support_level,
        "recognition_levels": recognition_level,
        "supervised_levels": supervised_level,
        "public_levels": public_level,






        "personals": personals,
        "essentials": essentials,
        "no_equipment": no_equipment,
        "pk": pk,

    }
    if request.method == "POST":
        print(request.POST)

        hotel = request.POST.get('accomodations', "None")
        room = request.POST.get('rooms', "None")
        dives = request.POST.getlist("dives", [])
        equipment = request.POST.getlist("equipments", [])
        date_arrival = request.POST.get('date_arrival')
        time_arrival = request.POST.get('time_arrival')
        print(room)

        reservation = Reservation()
        package = Package.objects.get(id=pk)

        reservation.package = package
        reservation.arrival_date = date_arrival
        reservation.arrival_time = time_arrival
        reservation.save()

        if dives:
            for dive in dives:
                dive_type = DiveType.objects.get(name=dive)
                res_dive = ReservationDives()
                res_dive.dives_name = dive_type
                res_dive.reservation = reservation
                res_dive.price = dive_type.price
                res_dive.save()

        if equipment:
            for eq in equipment:
                equipment_name = Equipement.objects.get(name=eq)
                res_equipment = ReservationEquipments()
                res_equipment.equipment_name = equipment_name
                res_equipment.reservation = reservation
                res_equipment.price = dive_type.price
                res_equipment.save()

        hotel_type = Accomodation.objects.get(name=hotel)
        room_type = Room.objects.get(name=room)
        res_hotel = ReservationHotel()
        res_hotel.hotel = hotel_type
        res_hotel.room = room_type
        res_hotel.price_hotel = hotel_type.price
        res_hotel.price_room = room_type.price
        res_hotel.reservation = reservation
        res_hotel.save()

        package = Package.objects.get(id=pk)

        return redirect(reverse('packages:registration-summary', kwargs={'pk': reservation.pk}))

    return render(request, "package_registration/package_registration.html", context)


class SummaryView(LoginRequiredMixin, generic.FormView):
    template_name = "package_registration/purchase_summary.html"
    form_class = dummy

    def get_context_data(self, **kwargs):
        total_price_dives = 0
        total_price_equipment = 0
        total_price_hotel = 0
        total_price = 0
        pk = self.kwargs["pk"]
        context = super(SummaryView, self).get_context_data(**kwargs)
        dives = ReservationDives.objects.filter(reservation=pk)
        equipments = ReservationEquipments.objects.filter(reservation=pk)
        hotel = ReservationHotel.objects.get(reservation=pk)
        reservation = Reservation.objects.get(pk=pk)
        package = Package.objects.get(name=reservation.package)

        package_price = package.price

        for dive in dives:
            total_price_dives += dive.price

        for eq in equipments:
            total_price_equipment += eq.price

        total_price_hotel = hotel.price_hotel+hotel.price_room

        total_price = total_price_dives+total_price_equipment + \
            total_price_hotel+package_price

        context.update({
            "dives": dives,
            "equipments": equipments,
            "hotel": hotel,
            "reservation": reservation,
            "package_price": package_price,
            "price_hotel": total_price_hotel,
            "price_equipment": total_price_equipment,
            "price_dives": total_price_dives,
            "total_price": total_price

        })

        return context

    def post(self, request, *args, **kwargs):
        pk = self.kwargs["pk"]
        reservation = Reservation.objects.get(pk=pk)
        total_price = request.POST.get("price")

        reservation.user = self.request.user
        reservation.total_price = total_price
        reservation.save()

        return redirect(reverse('packages:registration-payment', kwargs={'pk': pk}))


class PaymentView(generic.FormView):
    template_name = "package_registration/payment.html"
    form_class = dummy

    def post(self, request, *args, **kwargs):
        total_price = 0
        pk = self.kwargs["pk"]
        context = super(PaymentView, self).get_context_data(**kwargs)
        dives = ReservationDives.objects.filter(reservation=pk)
        equipments = ReservationEquipments.objects.filter(reservation=pk)
        hotel = ReservationHotel.objects.get(reservation=pk)
        reservation = Reservation.objects.get(pk=pk)
        package = Package.objects.get(name=reservation.package)

        plaintext = get_template(
            'package_registration/confirmation_email.txt').render()
        htmly = get_template(
            'package_registration/confirmation_email.html').render()

        subject, from_email, to = 'Your Purchase Information', settings.EMAIL_HOST_USER, self.request.user

        msg = EmailMultiAlternatives(subject, plaintext, from_email, [to])
        msg.attach_alternative(htmly, "text/html")
        msg.send()
        return redirect(reverse('landing:home'))

package_registration/templates/package_registration/confirmation_email.html
<!DOCTYPE html>
<html lang="en">


<body>
    <h1 style="color:red">Thank you for booking your trip with us</h1>

    <h2>You can check your order <a href="http://127.0.0.1:8000/user/orders/">here</a></h2>
</body>

</html>

package_registration/templates/package_registration/purchase_summary.html
{% extends 'base_registration.html' %}
{% load static %}

{% block title %}<title>Summary</title>{% endblock title %}
{% block links %}

<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}" />
<link rel="stylesheet" href="{% static 'css/fonts.css' %}" />
<link rel="stylesheet" href="{% static 'css/style.css' %}" />
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css"
    integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous" />

<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" />
<link href="https://fonts.googleapis.com/css?family=Nunito:400,400i,600,600i,700,700i%7cPermanent+Marker"
    rel="stylesheet" />
<link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700,800,900" rel="stylesheet">

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

<link href="{% static 'css/theme.css' %}" rel="stylesheet" type="text/css" media="all" />

<style>
    .checkbox-lg .custom-control-label::before,
    .checkbox-lg .custom-control-label::after {
        top: .8rem;
        width: 1.55rem;
        height: 1.55rem;
    }

    .checkbox-lg .custom-control-label {
        padding-top: 13px;
        padding-left: 6px;
    }


    .checkbox-xl .custom-control-label::before,
    .checkbox-xl .custom-control-label::after {
        top: 1.2rem;
        width: 1.85rem;
        height: 1.85rem;
    }

    .checkbox-xl .custom-control-label {
        padding-top: 23px;
        padding-left: 10px;
    }
</style>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script>
    $(document).ready(function () {
        $('#accomodations').change(function () {
            if ($(this).val() == "None") {

                $("#rooms").prop("disabled", true)
                $("#rooms").val("None")

            } else {
                $("#rooms").prop("disabled", false)
                $("#rooms").val("Single")



            };
        })

        var max_limit = 3; // Max Limit
        $(document).ready(function () {
            $(".check:input:checkbox").each(function (index) {
                this.checked = (".check:input:checkbox" < max_limit);
            }).change(function () {
                if ($(".check:input:checkbox:checked").length > max_limit) {
                    this.checked = false;
                }
            });
        });





    });
</script>
{% endblock links %}

{% block content %}
<section class="height-100 bg-gradient-3">
    <div class="position-absolute text-center sticky-top w-100 p-3">
        <a href="{% url 'landing:packages' %}" class="h3 text-white">
            Go back to packages selection
        </a>
    </div>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-xl-9 col-lg-10">
                <form class="wizard card" method="POST" , action="">
                    {% csrf_token %}
                    <ul class="nav nav-tabs card-header text-center bg-light p-0">
                        <li class="nav-item flex-fill">
                            <a class="nav-link" href="#first">5. Confirmation</a>
                        </li>


                    </ul>

                    <div class="tab-content">
                        <div id="first">
                            <div class="card-body py-4">
                                <div class="text-center">
                                    <span class="h3 d-block">Package details</span>
                                    <span class="h5 d-block m-3">Arrival date : {{reservation.arrival_date}}</span>
                                    <p class="h5 d-block m-3">{{reservation.package}}</p>
                                    <p class="lead text-danger ">Package base Price :
                                        {{package_price}} $</p>
                                    <p class="lead text-danger ">Total Dive Price : {{price_dives}} $
                                    </p>
                                    <p class="lead text-danger ">Total Equipment Price :
                                        {{price_equipment}} $</p>
                                    <p class="lead text-danger ">Hotel Price : {{price_hotel}} $</p>
                                    <p class="lead text-danger font-weight-bold">Total Price : {{total_price}} $</p>
                                </div>

                                <div class="row">
                                    <div class="col-sm mb-3 mb-sm-0 justify-content-center text-center">

                                        <div class="text-center">
                                            <span class="h4 d-block mt-5 mb-3 text-primary">Dives</span>

                                        </div>

                                        <table class="table">
                                            <thead class="thead-light">
                                                <tr>

                                                    <th scope="col">Dive Type</th>
                                                    <th scope="col">Price</th>

                                                </tr>
                                            </thead>

                                            <tbody>
                                                {% for dive in dives %}
                                                <tr>
                                                    <td class="text-center"> {{dive.dives_name}}</td>
                                                    <td class="text-right"> {{dive.price}} $</td>

                                                </tr>
                                                {% endfor %}


                                            </tbody>
                                        </table>
                                        <div class="text-center">
                                            <span class="h4 d-block mt-5 mb-3 text-primary">Equipments</span>

                                        </div>
                                        <table class="table">

                                            <thead class="thead-light">
                                                <tr>

                                                    <th scope="col">Equipment</th>
                                                    <th scope="col">Price</th>

                                                </tr>
                                            </thead>

                                            <tbody>
                                                {% for equipment in equipments %}
                                                <tr>
                                                    <td class="text-center"> {{equipment.equipment_name}}</td>
                                                    <td class="text-right"> {{equipment.price}} $</td>

                                                </tr>
                                                {% endfor %}



                                            </tbody>
                                        </table>
                                        <div class="text-center">
                                            <span class="h4 d-block mt-5 mb-3 text-primary">Hotel</span>

                                        </div>
                                        <table class="table">

                                            <thead class="thead-light">
                                                <tr>

                                                    <th scope="col">Hotel</th>
                                                    <th scope="col">Room</th>
                                                    <th scope="col">Price</th>


                                                </tr>
                                            </thead>

                                            <tbody>

                                                <tr>
                                                    <td> {{hotel.hotel}}</td>
                                                    <td> {{hotel.room}}</td>
                                                    <td class="text-right">{{price_hotel}} $</td>

                                                </tr>


                                            </tbody>
                                        </table>
                                        <form method="POST" action="">
                                            <input name="pk" value={{reservation.pk}} hidden>
                                            <input name="price" value={{total_price}} hidden>
                                            <button class="btn btn-primary text-white text-capitalize mt-5"
                                                type="submit">Confirm</button>
                                        </form>
                                        </br>
                                        <a href="{% url 'packages:package-registration' reservation.pk %}">Go back to
                                            {{reservation.package}}</a>
                                    </div>

                                </div>
                            </div>
                        </div>




                    </div>
                </form>
                <div class="card-footer text-center">
                    <small class="text-white">Having trouble filling out this form?
                        <a href="#" class="font-weight-bold">Contact Support</a>
                    </small>
                </div>
            </div>
        </div>
    </div>
</section>



{% endblock content %}
{% block script %}
<script src="{% static 'js/core.min.js' %}"></script>
<script src="{% static 'js/script.js' %}"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js"
    integrity="sha384-SR1sx49pcuLnqZUnnPwx6FCym0wLsk5JZuNx2bPPENzswTNFaQU1RDvt3wT4gWFG" crossorigin="anonymous">
</script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.min.js"
    integrity="sha384-j0CNLUeiqtyaRmlzUHCPZ+Gy5fQu0dQ6eZ/xAww941Ai1SxSY+0EQqNXNE6DZiVc" crossorigin="anonymous">
</script>
<script type="text/javascript" src="{% static '/js/jquery.min.js' %}"></script>
<script type="text/javascript" src="{% static '/js/popper.min.js' %}"></script>
<script type="text/javascript" src="{% static '/js/prism.js' %}"></script>
<script type="text/javascript" src="{% static '/js/smooth-scroll.polyfills.js' %}"></script>
<script type="text/javascript" src="{% static '/js/scrollMonitor.js' %}"></script>
<script type="text/javascript" src="{% static '/js/bootstrap.js' %}"></script>
<script type="text/javascript" src="{% static '/js/clipboard.js' %}"></script>
<script type="text/javascript" src="{% static '/js/jquery.countdown.min.js' %}"></script>
<script type="text/javascript" src="{% static '/js/flickity.pkgd.min.js' %}"></script>
<script type="text/javascript" src="{% static '/js/isotope.pkgd.min.js' %}"></script>
<script type="text/javascript" src="{% static '/js/jquery.smartWizard.min.js' %}"></script>
<script type="text/javascript" src="{% static '/js/jquery.fancybox.min.js' %}"></script>
<script type="text/javascript" src="{% static '/js/zoom.min.js' %}"></script>
<script type="text/javascript" src="{% static '/js/theme.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>

{% endblock script %}

</html>