adminop/urls.py
from adminop.views import OperatorDetailsView, OperatorView
from userapp.views import OrderDetailsView, OrderView
from django.urls import path

app_name = "operator"


urlpatterns = [
    path('', OperatorView.as_view(),
         name="reservations"),
    path('reservation//<int:pk>', OperatorDetailsView.as_view(),
         name="reservation-detail"),
]

courses/urls.py
from .views import (
    RescueScubaView,
    AdvancedScubaView,
    NitroxView,
    OpenWaterView,
    MasterScubaView,
    FirstAidCourseView,
    FullFaceView,
    PublicSafetyView,
    LionFishView,
    DiveMasterView,
    InstructorView,
    CrossOverView,
    TrainerView,
    AidInstructorView,
    DirectorView,
    IntroTechnicalView,
    MixedGasView,
    RebreatherView,
    OverheadView,
    DVPView
)
from django.urls import path

app_name="courses"

urlpatterns = [
    path('rescue/',RescueScubaView.as_view(), name="rescue"),
    path('advanced/',AdvancedScubaView.as_view(), name="advanced"),
    path('nitrox/',NitroxView.as_view(), name="nitrox"),
    path('open_water/',OpenWaterView.as_view(), name="open-water"),
    path('master_scuba/',MasterScubaView.as_view(), name="master-scuba"),
    path('first_aid_course/',FirstAidCourseView.as_view(), name="aid-course"),
    path('full-face/',FullFaceView.as_view(), name="full-face"),
    path('public-safety/',PublicSafetyView.as_view(), name="public-safety"),
    path('hunter/',LionFishView.as_view(), name="hunter"),
    path('divemaster/',DiveMasterView.as_view(), name="divemaster"),
    path('instructor/',InstructorView.as_view(), name="instructor"),
    path('instructor_crossover/',CrossOverView.as_view(), name="instructor-crossover"),
    path('instructor_trainer/',TrainerView.as_view(), name="instructor-trainer"),
    path('fa_intstructor/',AidInstructorView.as_view(), name="fa-instructor"),
    path('course_director/',DirectorView.as_view(), name="director"),
    path('intro_tech/',IntroTechnicalView.as_view(), name="intro-tech"),
    path('mixed_gas/',MixedGasView.as_view(), name="mixed-gas"),
    path('rebreather/',RebreatherView.as_view(), name="rebreather"),
    path('overhead/',OverheadView.as_view(), name="overhead"),
    path('DVP/',DVPView.as_view(), name="DVP"),


    


    
]

fyfproject/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LoginView, LogoutView
from landing.views import SignUpView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("landing.urls", namespace="landing")),
    path('courses/', include("courses.urls", namespace="courses")),
    path('user/', include("userapp.urls", namespace="userapp")),
    path('operator/', include("adminop.urls", namespace="operator")),
    path('packages/', include("package_registration.urls", namespace="packages")),
    path('account/signup/', SignUpView.as_view(), name="signup"),
    path('accounts/', include('allauth.urls')),

]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

landing/urls.py
from .views import landing_home, coming_soon, packages_page, CourseView
from django.urls import path

app_name = "landing"

urlpatterns = [
    path('', landing_home, name="home"),
    path('packages', packages_page, name="packages"),
    path('courses', CourseView.as_view(), name="courses"),
    path('coming_soon/', coming_soon, name="coming-soon"),




]

userapp/urls.py
from userapp.views import OrderDetailsView, OrderView
from django.urls import path

app_name = "userapp"


urlpatterns = [
    path('orders/', OrderView.as_view(),
         name="orders"),
    path('orders/<int:pk>', OrderDetailsView.as_view(),
         name="order-detail"),
]

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
  {% block title %}{% endblock title %}
  <meta name="format-detection" content="telephone=no" />
  <meta name="viewport"
    content="width=device-width, height=device-height, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <link rel="icon" href="{% static 'images/favicon.ico' %}" <meta charset="utf-8" />
  <!-- Stylesheets-->
  <link rel="stylesheet" type="text/css"
    href="//fonts.googleapis.com/css?family=Montserrat:400,500,600,700%7CPoppins:400%7CTeko:300,400" />
  {% block links %}{% endblock links %}
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous" />
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js"
    integrity="sha384-SR1sx49pcuLnqZUnnPwx6FCym0wLsk5JZuNx2bPPENzswTNFaQU1RDvt3wT4gWFG" crossorigin="anonymous">
  </script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.min.js"
    integrity="sha384-j0CNLUeiqtyaRmlzUHCPZ+Gy5fQu0dQ6eZ/xAww941Ai1SxSY+0EQqNXNE6DZiVc" crossorigin="anonymous">
  </script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous">
  </script>
</head>

<body>
  <div class="preloader">
    <div class="preloader-body">
      <div class="cssload-container">
        <div class="cssload-speeding-wheel"></div>
      </div>
      <p>Loading...</p>
    </div>
  </div>
  <div class="page">
    <!-- Page Header-->
    <!-- RD Navbar-->
    <div class="rd-navbar-wrap">
      <nav class="rd-navbar rd-navbar-corporate" data-layout="rd-navbar-fixed" data-sm-layout="rd-navbar-fixed"
        data-md-layout="rd-navbar-fixed" data-md-device-layout="rd-navbar-fixed" data-lg-layout="rd-navbar-static"
        data-lg-device-layout="rd-navbar-fixed" data-xl-layout="rd-navbar-static"
        data-xl-device-layout="rd-navbar-static" data-xxl-layout="rd-navbar-static"
        data-xxl-device-layout="rd-navbar-static" data-lg-stick-up-offset="46px" data-xl-stick-up-offset="46px"
        data-xxl-stick-up-offset="106px" data-lg-stick-up="true" data-xl-stick-up="true" data-xxl-stick-up="true">
        <div class="rd-navbar-collapse-toggle rd-navbar-fixed-element-1" data-rd-navbar-toggle=".rd-navbar-collapse">
          <span></span>
        </div>
        <div class="rd-navbar-aside-outer">
          <div class="rd-navbar-aside">
            <!-- RD Navbar Panel-->
            <div class="rd-navbar-panel">
              <!-- RD Navbar Toggle-->
              <button class="rd-navbar-toggle" data-rd-navbar-toggle=".rd-navbar-nav-wrap"><span></span></button>
              <!-- RD Navbar Brand-->
              <div class="rd-navbar-brand">
                <!--Brand-->
                <a class="brand" href="index.html"><img src="{% static 'imageslb/logo.svg' %}" alt="" width="225"
                    height="18"></a>

              </div>

            </div>
            {% if request.user.is_authenticated %}
            <div class="rd-navbar-aside-right rd-navbar-collapse">

              <ul class="rd-navbar-corporate-contacts">
                <li>
                  <div class="unit unit-spacing-xs pt-4">
                    <div class="dropdown">
                      <button class="btn dropdown-toggle" type="button" id="dropdownMenuButton1"
                        data-bs-toggle="dropdown" aria-expanded="false">
                        <i class="fa fa-user"></i>
                      </button>
                      <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                        <li><a class="dropdown-item" href="#">Account</a></li>
                        <li><a class="dropdown-item" href="#">Profile</a></li>



                      </ul>
                    </div>
                    <div class="unit-body pt-2 ">
                      <h6 class="h6 text-capitalize font-weight-normal">{{request.user.first_name}}
                        {{request.user.last_name}}</h6>
                    </div>
                  </div>
                </li><a class="button button-md button-default-outline-2 button-ujarak"
                  href="{% url 'account_logout' %}">Logout</a>
            </div>
            {% else %}
            <div class="rd-navbar-aside-right rd-navbar-collapse">
              <ul class="rd-navbar-corporate-contacts">
                <li>
                  <div class="unit unit-spacing-xs">
                    <div class="unit-left"><span class="icon fa fa-clock"></span></div>
                    <div class="unit-body"><a class="link-phone" href="tel:#">9:00am - 5:00pm</a></div>
                  </div>
                </li>
              </ul>

              <ul class="rd-navbar-corporate-contacts">
                <li>
                  <div class="unit unit-spacing-xs">
                    <div class="unit-left"><span class="icon fa fa-clock"></span></div>
                    <div class="unit-body"><a class="link-phone" href="tel:#">01-487 866</a></div>
                  </div>
                </li>




              </ul><a class="button button-md button-default-outline-2 button-ujarak"
                href="{% url 'account_login' %}">Login</a>
            </div>
            {% endif %}
          </div>
        </div>
        <div class="rd-navbar-main-outer">
          <div class="rd-navbar-main">
            <div class="rd-navbar-nav-wrap">
              <div class="mb-2">
                <ul class="list-inline list-inline-md rd-navbar-corporate-list-social">
                  <li><a class="icon fa fa-facebook" href="#"></a></li>
                  <li><a class="icon fa fa-twitter" href="#"></a></li>
                  <li><a class="icon fa fa-google-plus" href="#"></a></li>
                  <li><a class="icon fa fa-instagram" href="https://www.instagram.com/findyourfinsinlebanon/"></a></li>
                </ul>
              </div>
              <!-- RD Navbar Nav-->
              <ul class="rd-navbar-nav">
                <li class="rd-nav-item"><a class="rd-nav-link" href={% url 'landing:home' %}>Home</a>
                </li>
                <li class="rd-nav-item"><a class="rd-nav-link" href="{% url 'landing:packages' %}">Packages</a>
                </li>
                <li class="rd-nav-item"><a class="rd-nav-link" href="{% url 'landing:courses' %}">Courses</a>
                </li>
                <li class="rd-nav-item"><a class="rd-nav-link" href="{% url 'landing:coming-soon' %}">FAQ</a>
                </li>
                <li class="rd-nav-item"><a class="rd-nav-link" href="{% url 'landing:coming-soon' %}">Contact Us</a>
                </li>
                {% if request.user.is_authenticated %}
                <li class="rd-nav-item"><a class="rd-nav-link" href="{% url 'userapp:orders' %}"> Reservations</a>
                </li>
                {% endif %}

              </ul>
            </div>
          </div>
        </div>
      </nav>
    </div>
    </header>
    {% block content %} {% endblock content %}

    <!-- Scripts-->
</body>
{% block script %} {% endblock script %}

</html>

templates/base_login.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
  {% block title %}{% endblock title %}
  <meta name="format-detection" content="telephone=no" />
  <meta name="viewport"
    content="width=device-width, height=device-height, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <link rel="icon" href="{% static 'images/favicon.ico' %}" <meta charset="utf-8" />
  <!-- Stylesheets-->
  <link rel="stylesheet" type="text/css"
    href="//fonts.googleapis.com/css?family=Montserrat:400,500,600,700%7CPoppins:400%7CTeko:300,400" />
  {% block links %}{% endblock links %}
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous" />
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js"
    integrity="sha384-SR1sx49pcuLnqZUnnPwx6FCym0wLsk5JZuNx2bPPENzswTNFaQU1RDvt3wT4gWFG" crossorigin="anonymous">
  </script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.min.js"
    integrity="sha384-j0CNLUeiqtyaRmlzUHCPZ+Gy5fQu0dQ6eZ/xAww941Ai1SxSY+0EQqNXNE6DZiVc" crossorigin="anonymous">
  </script>
</head>

<body>
  <div class="preloader">
    <div class="preloader-body">
      <div class="cssload-container">
        <div class="cssload-speeding-wheel"></div>
      </div>
      <p>Loading...</p>
    </div>
  </div>
  <div class="page">{% block content %} {% endblock content %}</div>
  <!-- Scripts-->
</body>
{% block script %} {% endblock script %}

</html>

templates/base_registration.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    {% block title %}{% endblock title %}
    <meta name="format-detection" content="telephone=no" />
    <meta name="viewport"
        content="width=device-width, height=device-height, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <link rel="icon" href="{% static 'images/favicon.ico' %}" <meta charset="utf-8" />
    <!-- Stylesheets-->
    <link rel="stylesheet" type="text/css"
        href="//fonts.googleapis.com/css?family=Montserrat:400,500,600,700%7CPoppins:400%7CTeko:300,400" />
    {% block links %}{% endblock links %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous" />
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js"
        integrity="sha384-SR1sx49pcuLnqZUnnPwx6FCym0wLsk5JZuNx2bPPENzswTNFaQU1RDvt3wT4gWFG" crossorigin="anonymous">
    </script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.min.js"
        integrity="sha384-j0CNLUeiqtyaRmlzUHCPZ+Gy5fQu0dQ6eZ/xAww941Ai1SxSY+0EQqNXNE6DZiVc" crossorigin="anonymous">

    </script>


</head>

<body>
    <div class="preloader">
        <div class="preloader-body">
            <div class="cssload-container">
                <div class="cssload-speeding-wheel"></div>
            </div>
            <p>Loading...</p>
        </div>
    </div>
    <div class="page">{% block content %} {% endblock content %}</div>
    <!-- Scripts-->
</body>
{% block script %} {% endblock script %}


</html>

templates/baseop.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
  {% block title %}{% endblock title %}
  <meta name="format-detection" content="telephone=no" />
  <meta name="viewport"
    content="width=device-width, height=device-height, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <link rel="icon" href="{% static 'images/favicon.ico' %}" <meta charset="utf-8" />
  <!-- Stylesheets-->
  <link rel="stylesheet" type="text/css"
    href="//fonts.googleapis.com/css?family=Montserrat:400,500,600,700%7CPoppins:400%7CTeko:300,400" />
  {% block links %}{% endblock links %}
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous" />
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js"
    integrity="sha384-SR1sx49pcuLnqZUnnPwx6FCym0wLsk5JZuNx2bPPENzswTNFaQU1RDvt3wT4gWFG" crossorigin="anonymous">
  </script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.min.js"
    integrity="sha384-j0CNLUeiqtyaRmlzUHCPZ+Gy5fQu0dQ6eZ/xAww941Ai1SxSY+0EQqNXNE6DZiVc" crossorigin="anonymous">
  </script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous">
  </script>
</head>

<body>
  <div class="preloader">
    <div class="preloader-body">
      <div class="cssload-container">
        <div class="cssload-speeding-wheel"></div>
      </div>
      <p>Loading...</p>
    </div>
  </div>
  <div class="page">
    <!-- Page Header-->
    <!-- RD Navbar-->
    <div class="rd-navbar-wrap">
      <nav class="rd-navbar rd-navbar-corporate" data-layout="rd-navbar-fixed" data-sm-layout="rd-navbar-fixed"
        data-md-layout="rd-navbar-fixed" data-md-device-layout="rd-navbar-fixed" data-lg-layout="rd-navbar-static"
        data-lg-device-layout="rd-navbar-fixed" data-xl-layout="rd-navbar-static"
        data-xl-device-layout="rd-navbar-static" data-xxl-layout="rd-navbar-static"
        data-xxl-device-layout="rd-navbar-static" data-lg-stick-up-offset="46px" data-xl-stick-up-offset="46px"
        data-xxl-stick-up-offset="106px" data-lg-stick-up="true" data-xl-stick-up="true" data-xxl-stick-up="true">
        <div class="rd-navbar-collapse-toggle rd-navbar-fixed-element-1" data-rd-navbar-toggle=".rd-navbar-collapse">
          <span></span>
        </div>
        <div class="rd-navbar-aside-outer">
          <div class="rd-navbar-aside">
            <!-- RD Navbar Panel-->
            <div class="rd-navbar-panel">
              <!-- RD Navbar Toggle-->
              <button class="rd-navbar-toggle" data-rd-navbar-toggle=".rd-navbar-nav-wrap"><span></span></button>
              <!-- RD Navbar Brand-->
              <div class="rd-navbar-brand">
                <!--Brand-->
                <a class="brand" href="index.html"><img src="{% static 'imageslb/logo.svg' %}" alt="" width="225"
                    height="18"></a>

              </div>

            </div>
            {% if request.user.is_authenticated %}
            <div class="rd-navbar-aside-right rd-navbar-collapse">

              <ul class="rd-navbar-corporate-contacts">
                <li>
                  <div class="unit unit-spacing-xs pt-4">

                    <div class="unit-body pt-2 ">
                      <h6 class="h6 text-capitalize font-weight-normal">{{request.user.first_name}}
                        {{request.user.last_name}}</h6>
                    </div>
                  </div>
                </li><a class="button button-md button-default-outline-2 button-ujarak"
                  href="{% url 'account_logout' %}">Logout</a>
            </div>
            {% else %}
            <div class="rd-navbar-aside-right rd-navbar-collapse">
              <ul class="rd-navbar-corporate-contacts">
                <li>
                  <div class="unit unit-spacing-xs">
                    <div class="unit-left"><span class="icon fa fa-clock"></span></div>
                    <div class="unit-body"><a class="link-phone" href="tel:#">9:00am - 5:00pm</a></div>
                  </div>
                </li>
              </ul>

              <ul class="rd-navbar-corporate-contacts">
                <li>
                  <div class="unit unit-spacing-xs">
                    <div class="unit-left"><span class="icon fa fa-clock"></span></div>
                    <div class="unit-body"><a class="link-phone" href="tel:#">01-487 866</a></div>
                  </div>
                </li>




              </ul><a class="button button-md button-default-outline-2 button-ujarak"
                href="{% url 'account_login' %}">Login</a>
            </div>
            {% endif %}
          </div>
        </div>

      </nav>
    </div>
    </header>
    {% block content %} {% endblock content %}

    <!-- Scripts-->
</body>
{% block script %} {% endblock script %}

</html>